---
- hosts: master:slave
  become: yes
  roles:
    - container_features
    - create_user
    - dphys_swapfile
    - etc_config

- hosts: localhost
  roles:
    - bootstrap_k3sup
    - k3s_cluster
  vars_files:
    - vars/vaultfile.yml
