---
- name: Create agent and join {{groups.master.0}} with k3s {{k3s_version}}
  command:
  args:
    argv:
      - k3sup
      - join
      - --server-ip
      - "{{hostvars[groups.master.0].ansible_facts.eth0.ipv4.address}}"
      - --ip
      - "{{hostvars[item].ansible_default_ipv4.address}}"
      - --ssh-key
      - "{{ssh_key}}"
      - --user
      - "{{k3s_username}}"
      - --k3s-version
      - "{{k3s_version}}"
  with_items: "{{ groups['slave'] }}"
  when: master_created is succeeded and http_api_result is succeeded
  register: slave_joined

- name: Debug report of slave joined
  debug: var=slave_joined
  when: slave_joined is failed or debug_nodes
