---
- name: Verify cgroup flags are enabled
  lineinfile:
    path: /boot/cmdline.txt
    backrefs: yes
    state: present
    regexp: '^(.*) {{item}}(.*)$'
    backup: yes
    line: '\g<1> {{item}}\g<2>'
  with_items:
    - 'cgroup_enable=cpuset'
    - 'cgroup_enable=memory'
    - 'cgroup_memory=1'
  register: cgroup_flags
  when: "ansible_lsb.id == 'Raspbian' and ansible_kernel is version('4.6', '>=')"
  changed_when: cgroup_flags.rc is defined and cgroup_flags.rc != 0
  notify: Reboot
